version: "3.9"
name: "dbtrials"
services:


  backend:
    build:
      context: .
      dockerfile: Containerfile.backend
    image: dbtrials-backend:latest
    container_name: dbtrials-backend
    volumes:
      - dbtrials-db:/app/dbtrials/db.sqlite3
      - staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=dbtrials.settings
      - SECRET_KEY=change-me-in-production
      - DEBUG=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
    networks:
      - dbtrials-net
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Containerfile.frontend
    image: dbtrials-frontend:latest
    container_name: dbtrials-frontend
    networks:
      - dbtrials-net
    restart: unless-stopped

networks:
  dbtrials-net:
    driver: bridge

volumes:
  dbtrials-db:
  staticfiles:
