FROM docker.io/python:3.13-slim

RUN pip install --quiet poetry
COPY pyproject.toml /
COPY dbtrials/ /app/

WORKDIR /app
RUN poetry config virtualenvs.create false --quiet && \
    poetry install --only main --quiet

CMD python manage.py migrate && \
    python manage.py collectstatic --noinput && \
    gunicorn dbtrials.wsgi:application --bind 0.0.0.0:8000 --workers 2