# Generated by Django 6.0.6 on 2026-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0004_itemtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="item_class",
            field=models.CharField(
                choices=[("rentable", "ausleihbar"), ("consumable", "verbrauchbar")],
                default="rentable",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentalaction",
            name="action",
            field=models.CharField(
                choices=[("rent", "Ausleihe"), ("return", "Rückgabe")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Benutzer"), ("admin", "Administrator")],
                default="user",
                max_length=10,
            ),
        ),
    ]
