# Generated by Django 6.0.6 on 2026-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0005_item_class_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtype",
            name="item_class",
            field=models.CharField(
                choices=[("rentable", "ausleihbar"), ("consumable", "verbrauchbar")],
                max_length=20,
            ),
        ),
    ]
