# Generated by Django 6.0.6 on 2026-07-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0008_revert_rename_back_to_building_rentalgroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Building",
            new_name="Packstreet",
        ),
        migrations.CreateModel(
            name="Cookinggroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("group_number", models.CharField(max_length=50, unique=True)),
                (
                    "packstreet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="dbtrials.packstreet",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="rental",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentals",
                to="dbtrials.cookinggroup",
            ),
        ),
        migrations.AlterField(
            model_name="rentalaction",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="dbtrials.cookinggroup",
            ),
        ),
        migrations.DeleteModel(
            name="RentalGroup",
        ),
    ]
