# Generated by Django 6.0.6 on 2026-07-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0009_rename_building_packstreet_cookinggroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("rent", "Ausleihe"),
                    ("return", "Rückgabe"),
                    ("correct", "Korrektur"),
                ],
                max_length=10,
            ),
        ),
    ]
