# Generated by Django 6.0.6 on 2026-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0010_add_correct_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalaction",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
