# Generated by Django 6.0.6 on 2026-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0011_rentalaction_signed_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_consumables",
            field=models.BooleanField(default=True),
        ),
    ]
