# Generated by Django 6.0.7 on 2026-07-11 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0014_add_user_selected_packstreet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemtype",
            options={"ordering": ["-item_class", "created_at"]},
        ),
        migrations.AddField(
            model_name="itemtype",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
