# Generated by Django 6.0.7 on 2026-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0015_alter_itemtype_options_itemtype_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
