# Generated by Django 6.0.7 on 2026-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0016_rental_quantity_allow_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prefer_rent",
            field=models.BooleanField(default=True),
        ),
    ]
