# Generated by Django 6.0.7 on 2026-07-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0017_add_user_prefer_rent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=40, unique=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crates",
                        to="dbtrials.cookinggroup",
                    ),
                ),
            ],
            options={
                "ordering": ["barcode"],
            },
        ),
    ]
