# Generated by Django 6.0.7 on 2026-07-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0020_seed_kiste_itemtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalaction",
            name="barcode",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]