# Generated by Django 6.0.7 on 2026-07-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0021_add_rentalaction_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="barcode_view",
            field=models.BooleanField(default=False),
        ),
    ]