# Generated by Django 6.0.7 on 2026-07-25 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0022_add_user_barcode_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crate",
            name="last_seen_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="crate",
            name="last_seen_with",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crates",
                to="dbtrials.cookinggroup",
            ),
        ),
        migrations.AlterField(
            model_name="rentalaction",
            name="barcode",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_packstreet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dbtrials.packstreet",
            ),
        ),
        migrations.CreateModel(
            name="Correction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="dbtrials.rentalaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
