# Generated by Django 6.0.7 on 2026-07-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0023_add_correction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalaction",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="rentalaction",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
