# Generated by Django 6.0.7 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0024_soft_delete_rentalaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalaction",
            name="action",
            field=models.CharField(
                choices=[("rent", "Ausleihe"), ("return", "Rückgabe")], max_length=10
            ),
        ),
    ]
