# Generated by Django 6.0.7 on 2026-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0025_alter_rentalaction_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalaction",
            name="barcode",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
    ]
