# Generated by Django 6.0.7 on 2026-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0026_alter_rentalaction_barcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packstreet",
            options={"ordering": ["display_priority", "name"]},
        ),
        migrations.AddField(
            model_name="packstreet",
            name="display_priority",
            field=models.FloatField(default=0.0),
        ),
    ]
