# Generated by Django 6.0.7 on 2026-07-28 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0027_add_packstreet_display_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crate",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
