# Generated by Django 6.0.7 on 2026-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0028_non_nullable_last_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crate",
            name="last_seen_at",
            field=models.DateTimeField(null=True),
        ),
    ]
