# Generated by Django 6.0.7 on 2026-07-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtrials", "0029_alter_crate_last_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="barcode_view",
            field=models.BooleanField(default=True),
        ),
    ]
